### ISSUE TITLE
Авторизация через соцсети не работает

### ISSUE THREAD

**Issue by gggrafff** [mil-ast/odo24#38]
![изображение](https://user-images.githubusercontent.com/19623897/162249551-708c6289-6c55-49b3-90f0-186fbd743e3b.png)
![изображение](https://user-images.githubusercontent.com/19623897/162249642-9ed11b95-e760-4a7b-98e0-1b63de63f9a6.png)
![изображение](https://user-images.githubusercontent.com/19623897/162249685-a24902c1-c9ab-484e-bba2-5fa685d19ef3.png)

**Comment by gggrafff** [comment]
Разобрался. Не работают только кнопки на главной странице. Со страницы авторизации работает. 
Кстати, традиционная регистрация с главной тоже не туда ведёт.

**Comment by mil-ast** [comment]
Исправлено. Но наблюдаются пока не понятные 500 в некоторых случаях, если адрес открывать напрямую без кеша и SW
